---
apiVersion: v1
kind: Service
metadata:
  annotations:
    jkube.io/git-url: https://github.com/Rastamart11/msa
    jkube.io/git-commit: 1d3fdfaa4bb7886c7a05d91a4aa9521f295258d5
    jkube.io/git-branch: master
    prometheus.io/path: /metrics
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
  labels:
    app: GetShoppingCart
    provider: jkube
    version: 0.0.1-SNAPSHOT
    group: com.erpsol.camel.invoke
  name: getshoppingcart
spec:
  ports:
  - name: sqlexec
    port: 9088
    protocol: TCP
    targetPort: 9088
  selector:
    app: GetShoppingCart
    provider: jkube
    group: com.erpsol.camel.invoke
  type: NodePort
